name: paper

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  paper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.8"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y -q -c conda-forge tectonic
          python -m pip install -U pip
          python -m pip install -U astropy
          python -m pip install https://github.com/astropy/astroquery/archive/master.zip
          python -m pip install git+https://github.com/rodluger/starry

      - name: Compile the paper
        shell: bash -l {0}
        run: |
          cd tex && make

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            tex/**.pdf