name: paper

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  paper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: starrynight
          environment-file: environment.yml
          python-version: "3.8"

      - name: Compile the paper
        shell: bash -l {0}
        run: |
          cd tex && make

      - name: Upload the paper
        uses: dfm/force-push-branch-action@v1
        with:
          branch-suffix: "-pdf"
          commit-message: "Committing automatically from GitHub Actions"
          path: |
            tex/**.pdf